### ISSUE TITLE
Fields with buttons look incorrectly after focusing button

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1917]
I think there was some CSS engine change in Blink, does not happen in Firefox eg.

![2_texts_nok](https://user-images.githubusercontent.com/3099142/76987812-176e0400-6944-11ea-97cc-a5d952186e70.png)

**Comment by mpfau** [comment]
This is a problem with the negative margin that we apply to the buttons container to right align the buttons correctly.

This seems to be triggered only by negative margins with flex layouts.

**Comment by charlag** [comment]
Seems like it's rolled back/fixed in Chrome Version 82.0.4085.1 (Dev) but still happens in 80.0.3987.149

**Comment by bedhub** [comment]
We will not fix it but keep this issue open until the fix has been released in stable chrome.

**Comment by bedhub** [comment]
Check if an update of electron fixes this issue

**Comment by ganthern** [comment]
still occurs in Electron 8.3.1 (Chromium 80.0.3987.165), next Electron version bump to 9.x.y should fix it (Chromium 83)

**Comment by charlag** [comment]
Test notes: check downloads and opening files on all platforms
