### ISSUE TITLE
Non-confidential event invites require password after saving

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2259]
1. Set _Default delivery_ to "Not confidential"
2. Create event, tab "GUESTS" and type/paste external email, **not using auto complete** so the padlock doesn't show
3. Tap "Save"
4. Confirm that external recipient got unencrypted invite.
5. Edit the event
6. Event is shown as confidential and cannot send out updates without providing password

**Expected behavior**
Event is not confidential

**Additional information**

 - Platform: Android app, Chromium on Linux
 - Version 3.76.7, 3.76.11, 3.77.1

Not happening on ~~browser~~ Firefox.

**Comment by johnbotris** [comment]
Seems to have been fixed by now? I can't reproduce it

**Comment by vitoreiji** [comment]
I can still reproduce it on 3.76.11 on Android and on Chromium on the Desktop.

**Comment by charlag** [comment]
@vitoreiji is this still relevant?

**Comment by vitoreiji** [comment]
I can no longer reproduce this.
