### ISSUE TITLE
Navigation bar disappears after sending draft email

### ISSUE THREAD

**Issue by alstr** [tutao/tutanota#2421]
**Bug in mobile app**

**Describe the bug**
After sending a message from the drafts folder, the navigation bar disappears. It is not possible to navigate to another folder and requires the app to be force closed.

**To Reproduce**
1. Write email message.
2. Click cancel, then save as draft.
3. Navigate to drafts folder, select message and send.
4. See screenshot.

![C6C35DDD-E76F-45A1-8E7F-36CEC1635FA2](https://user-images.githubusercontent.com/11612438/98858332-56fbda00-2458-11eb-99ac-dd3a7f69eff6.png)

**Expected behavior**
I would expect to be able to navigate to another folder after sending the message.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.1
 - Version 3.77.4

**Comment by charlag** [comment]
This is a very strange issue.
May I ask you to confirm that it only happens with drafts folder and only after sending (and not just opening empty folder)?

You can also swipe from the edge to open the menu I believe but of course we need to fix this.

**Comment by alstr** [comment]
Navigating to an empty drafts folder does not cause the issue to occur.

![794E7BC3-8E35-48D0-97E0-B9CFA54503AD](https://user-images.githubusercontent.com/11612438/98913679-990c3680-24bf-11eb-9c45-49a8c32faa0f.png)

The swipe gesture is not recognised when the issue does occur, so force close is the only option I can see.

**Comment by charlag** [comment]
Thanks for trying it out, I think some other error occurs (not just navigation disappearing) and the whole app breaks. We will investigate.

**Comment by alstr** [comment]
Some other observations:

* The issue doesn't occur when there is more than 1 draft in the folder. After sending a draft the view moves to the next draft.
* The issue doesn't occur on desktop.
* It looks like this is the preview pane that is appearing.

**Comment by charlag** [comment]
This should be fixed long time ago

**Comment by alstr** [comment]
This just happened again in the latest iOS build, so I think the problem remains.
![949C8564-4A06-4D11-AE04-527439E0F315](https://user-images.githubusercontent.com/11612438/132939915-a87b2d44-7e4c-4eac-bac8-11028e0ca0f5.png)

**Comment by charlag** [comment]
I can't reproduce it yet but let's reopen nonetheless

**Comment by alstr** [comment]
Still doing it today.
![5CDAFB0B-2386-402A-8F5A-72E28E2B7CFB](https://user-images.githubusercontent.com/11612438/181789163-27979d92-a9c2-444c-99f9-3790d4a228dd.png)

**Comment by wrdhub** [comment]
Hello! This issue is a bit old, and we have made UI changes since this was last discussed. I tried reproducing this on iOS and android and was not able to recreate this exact issue. Is this something that still happens for others?

**Comment by alstr** [comment]
I’ve not noticed it for a while. Don’t know if I could say it’s resolved. If I do notice it I’ll post here.
