### ISSUE TITLE
Mark as Spam button

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#343]
Add a "Mark as SPAM" button on the mail reading interface to create spam rules (based on sending address, sending server, etc.).

**Comment by asteintutao** [comment]
fixed in 2e0b8024f40610664b0f628014037ccf1f7c8899

**Comment by clort81** [comment]
Still not appearing for me:
![no_mark_as_spam](https://user-images.githubusercontent.com/51511737/119271319-5dd28900-bc01-11eb-93d2-3d914c4b24cf.png)

**Comment by jowlo** [comment]
If you click on any of the email addresses (eg `From:` or `Sender:` or `To:` and so on) you can "Add inbox rule" and select the destination folder as "Spam". This mails containing this field will be sorted into Spam for you from now on. There is no single button.

You can also "Report this email" if it does not contain any personal information. This will send the *unencrypted* mail to our server so that we can do better spam filtering directly when receiving mails. This will train our spam filters and thus everyone benefits.
