### ISSUE TITLE
Keychain errors on Linux

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3875]
User reports:

```
Error message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Stacktrace:
Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

```
CancelledError
Error message: user cancelled keychain unlock
Stacktrace:
CancelledError: user cancelled keychain unlock
at /opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:318969
at async Qc.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:652299)
at async Qc.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:13:652124)
```

Tumbleweed w/ GNOME:

```
Stacktrace:
Error: invalid mac
at os (file:///app/lib/tutanota/resources/app.asar/worker.js:1:38652)
at Wu.decrypt (file:///app/lib/tutanota/resources/app.asar/worker.js:12:130667)
at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:5590
at C.handleMessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:7598)
at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6851
at _worker.onmessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6431)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Desktop Environment: 
 - Version 3.91.9

**Additional context**
We started using keychain for credentials in 3.91.9

**Comment by pizzadude** [comment]
i have this issue with the flatpak on fedora kde

**Comment by Ahmed-E-86** [comment]
Hello! If there is an issue with the last update, could you please revert the last update until the issue is fixed? Thanks.

**Comment by Neyl-123** [comment]
I had the keychain problem on 3.91.9 (for details see issue #3877) and after updating to 3.91.10 it showed the message "The system keychain has been invalidated.Deleting stored credentials." which is intended to my understanding. I entered my credentials and TOTP but after trying to log in, I got this error:
```
Feedback v3.91.10 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.91.10
 Timestamp (UTC): Thu, 10 Feb 2022 09:07:06 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
 Error message: The file was externally modified
Stacktrace: 
Error: The file was externally modified
```
Then I closed the desktop client and reopened it and repeated the above but this time it worked and I could login. Going for another round I closed and reopend the client and got the above error again.

**Comment by Neyl-123** [comment]
@charlag It is the Flatpak version (as I wrote in #3877)

**Comment by charlag** [comment]
@Neyl-123 it should be fixed with 3.91.10-1

**Comment by Neyl-123** [comment]
3.91.10-1 did not fix it for me, but I think now it has a pattern.
The first time I enter my credentials (and TOTP) it works and I can log in. Then if I close the client but leave it running in the background (the status icon in the system status area is still present) it gives me the "The file was externally modified" Error. If I instead click on the status icon and click 'Quit' and reopen, it says "The system keychain has been invalidated. Deleting stored credentials.".
In order to test if this pattern holds true I did some more iterations and one time I got a endless loop (I let it run for 20 min.) while it said "Logging in" with the spinning red arrows. After closing the window it tried to get rid of the status icon with 'Quit' but it just persists. The interesting thing now is, that if I open the client I now have two status icons and despite of having to re-enter my credentials every time (I have 'Store password' checked) the login works now every time.
I have no clue what is going on but I hope this convoluted description can maybe somehow help to get to the bottom of this.

**Comment by HarlemSquirrel** [comment]
Yeah it seems to show  "The system keychain has been invalidated. Deleting stored credentials." every time I quit and reopen. I'm using the Flatpak version on ArchLinux with KDE

**Comment by Xathros1** [comment]
> Yeah it seems to show "The system keychain has been invalidated. Deleting stored credentials." every time I quit and reopen. I'm using the Flatpak version on ArchLinux with KDE

Yes, please reopen the issue, it's not fixed at all.

**Comment by Ahmed-E-86** [comment]
Yeah, it is not fixed with the latest release.

**Comment by Zlopez** [comment]
Can confirm that this is not fixed. It needs you to login every time you exit and start tutanota client again. It always creates a new session, which is annoying.

**Comment by charlag** [comment]
Is anyone in this thread experiencing this issue with AppImage build or is it only Flatpak for everyone?

**Comment by Zlopez** [comment]
I just tried the appimage and the appimage doesn't have this issue. When you close it and start it again it just logs you in automatically.

**Comment by pizzadude** [comment]
The appimage works fine. The flatpak has the issue.

**Comment by nitschis** [comment]
>  The appimage works fine. The flatpak has the issue.

The appimage only works fine on a few selected DEs, on KDE it does not work at all. Been weeks now without a client...

**Comment by pizzadude** [comment]
>The appimage only works fine on a few selected DEs, on KDE it does not work at all. Been weeks now without a client...
I use KDE Wayland on Fedora 35 and it works fine.

**Comment by nitschis** [comment]
> I use KDE Wayland on Fedora 35 and it works fine. But I also have gnome-keyring-daemon

So you made it work by installing parts of GNOME, that's what I said.

**Comment by pizzadude** [comment]
I already had parts of gnome installed.

**Comment by QEDeD** [comment]
On Pop!_OS 21.10, running the following flatpak version of Tutanota, I get the error "this systems keychain has been invalidated".

```
➜  ~ flatpak info com.tutanota.Tutanota 

Tutanota (preview) - Encrypted email client

          ID: com.tutanota.Tutanota
         Ref: app/com.tutanota.Tutanota/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.93.6
     License: GPL-3
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 244,6 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 3906bcfd548e6f7a75e4bb331a6e5cde31f31d82fff5463e7975196aefa93eb8
      Parent: 0692a7081b2f8838aa3afd28b122ba3aa4c31fae940898407c741110455e1f30
     Subject: update to v3.93.6 (a9fd4306)
        Date: 2022-03-11 10:34:41 +0000

```
```
➜  ~ flatpak run com.tutanota.Tutanota
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/tutanota/tutanota-desktop --type=zygote --enable-crashpad
the monkey has been patched
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.93.6
Gtk-Message: 21:46:07.467: Failed to load module "appmenu-gtk-module"
Gtk-Message: 21:46:07.514: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:46:07.514: Failed to load module "canberra-gtk-module"
resolving key... tutanota-vault
config up to date
[ApplicationWindow] startFile:  file:///app/lib/tutanota/resources/app.asar/index-desktop.html
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop//dictionaries/
default mailto handler: false
[DownloadManager] spellcheck-dictionary-initialized da
key tutanota-vault not found, generating a new one
sseInfo corrupted or not present, making sure pushEncSessionKeys and scheduled alarms are cleared
Resetting stored state
invalidating alarms for all windows
invalidating alarms for window 1
[45:0314/214607.686956:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[45:0314/214607.687033:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[45:0314/214607.687055:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[45:0314/214607.714147:ERROR:angle_platform_impl.cc(44)] Display.cpp:940 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[45:0314/214607.714191:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[45:0314/214607.714209:ERROR:gl_surface_egl.cc(1430)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[45:0314/214607.714226:ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[45:0314/214607.714855:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[88:0314/214607.726669:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2:0314/214607.741259:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0314/214607.749218:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:0314/214607.839811:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Webapp ready
no update info on disk, disabling updater.
[2:0314/214607.842557:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
desktop file exists, checking version...
resolving key... tutanota-credentials
scheduling to check sse in 1 seconds
scheduling to check sse in 1 seconds
key tutanota-credentials not found, generating a new one
scheduling to check sse in 10 seconds
sse info not available, skip reconnect

```

**Comment by Neyl-123** [comment]
Why is this still closed?

**Comment by Zlopez** [comment]
It still happens on KDE, but issue is gone on GNOME

**Comment by Neyl-123** [comment]
I have GNOME and it is surely not gone on v3.93.6

**Comment by Zlopez** [comment]
I'm running Tutanota v3.93.6 flatpak on GNOME 41.3 and don't have any issue. But I'm also running the same flatpak on KDE 5.15 and I still have issue with the credentials being forgot every time I restart the app.

**Comment by QEDeD** [comment]
@charlag is it possible for you to reopen the issue?

**Comment by charlag** [comment]
@QEDeD this is a Flatpak issue and should be solved with Flatpak

**Comment by charlag** [comment]
@Zlopez that is because KDE sometimes doesn't ship with secret storage which we *do require*

**Comment by Zlopez** [comment]
In flatpak case it shouldn't matter if there is KDE or GNOME running on the machine. But you are right in this case it's a flatpak issue only.

**Comment by charlag** [comment]
KWallet does not support org.freedesktop.secrets:
https://www.reddit.com/r/kde/comments/d8tjln/is_there_a_orgfreedesktopsecrets_implementation/f1cmejq/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by letscho123** [comment]
I still have this issue for the flatpak version, both on Fedora 35 KDE and Linux Mint Cinnamon 20.3
