### ISSUE TITLE
Android app v3.98.20 crash to home when click on show image

### ISSUE THREAD

**Issue by muchqs** [tutao/tutanota#4508]
**Bug in mobile app**

**Describe the bug**
Tutanota v3.98.20 on Android 9. When I click on "show" to load external images, the app crashes instantly to home screen with no error message. Strangely, it only happens with 1 particular email, other emails don't cause the crash. However, I have tested each version back to v3.98.12, and on v3.98.12 the email loads fine, no crash at all. So I think this is an issue with the app and changes done since v3.98.12. Bug reproduction rate 100%.

v3.98.20 - crash to home screen
v3.98.19 - crash to home screen
v3.98.18 - can't log in
v3.98.14 - can't log in
v3.98.12 - no problem at all

**To Reproduce**
1. Open the email
2. Click on "show" to load external images
3. Crash to home screen

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 9
 - Version 9.1.0

**Comment by diyaa59** [comment]
I can confirm this,

This happens on my android clients as well!!

**Comment by charlag** [comment]
I think it is fixed by 8736b692d0e7333338485eb88d9cfd017c17ff9b

please contact support and forward them an example of such an email after you load the images (on another device), right now it's not actionable

**Comment by diyaa59** [comment]
> I think it is fixed by [8736b69](https://github.com/tutao/tutanota/commit/8736b692d0e7333338485eb88d9cfd017c17ff9b)
> 
> please contact support and forward them an example of such an email after you load the images (on another device), right now it's not actionable

It is not fixed yet. However, I did forward the email to support!!

**Comment by charlag** [comment]
It is not released yet

**Comment by diyaa59** [comment]
> It is not released yet

My bad, I thought it was released 😄 .

**Comment by diyaa59** [comment]
Thank you very much for all the great work you guys do!!!

**Comment by charlag** [comment]
I will fix it, feel free to reopen if it doesn't work after the next release still
